export const WELCOME_COPY = {
  es: {
    brand: 'MASEYA',
    titleTop: 'Escanea lo que comes y lo que te pones',
    subtitle: 'y descubre si es bueno ',
    subtitleAccent: 'para ti',
    ex1Label: 'El mismo queso light',
    ex1a: '40 · sin alergias',
    ex1b: 'No apto · lactosa',
    ex2Label: 'La misma crema',
    ex2a: '84 · en general',
    ex2b: '68 · piel sensible',
    reach: 'Alergias · intolerancias · dieta halal · piel sensible',
    trust: 'Gratis · Sin descargas · Sin publicidad',
    cta: 'Escanear un producto',
    haveAccount: 'Ya tengo cuenta',
    howItWorks: 'Cómo funciona',
  },
  en: {
    brand: 'MASEYA',
    titleTop: 'Scan what you eat and what you put on',
    subtitle: 'and find out if it's good ',
    subtitleAccent: 'for you',
    ex1Label: 'The same light cheese',
    ex1a: '40 · no allergies',
    ex1b: 'Not suitable · lactose',
    ex2Label: 'The same cream',
    ex2a: '84 · overall',
    ex2b: '68 · sensitive skin',
    reach: 'Allergies · intolerances · halal diet · sensitive skin',
    trust: 'Free · No downloads · No ads',
    cta: 'Scan a product',
    haveAccount: 'I already have an account',
    howItWorks: 'How it works',
  },
  fr: {
    brand: 'MASEYA',
    titleTop: 'Scanne ce que tu manges et ce que tu mets',
    subtitle: 'et découvre si c'est bon ',
    subtitleAccent: 'pour toi',
    ex1Label: 'Le même fromage light',
    ex1a: '40 · sans allergies',
    ex1b: 'Non adapté · lactose',
    ex2Label: 'La même crème',
    ex2a: '84 · en général',
    ex2b: '68 · peau sensible',
    reach: 'Allergies · intolérances · régime halal · peau sensible',
    trust: 'Gratuit · Sans téléchargement · Sans pub',
    cta: 'Scanner un produit',
    haveAccount: 'J'ai déjà un compte',
    howItWorks: 'Comment ça marche',
  },
};
