export const WELCOME_COPY = {
  es: {
    brand: 'MASEYA',
    titleTop: 'Escanea lo que comes y lo que te pones',
    subtitle: 'y descubre si es bueno ',
    subtitleAccent: 'para ti',
    ex1Label: 'El mismo queso light',
    ex1aCond: 'Si no tienes alergias',
    ex1aVerdict: '40',
    ex1bCond: 'Si eres intolerante a la lactosa',
    ex1bVerdict: 'No apto',
    ex2Label: 'La misma crema',
    ex2aCond: 'Si tu piel es normal',
    ex2aVerdict: '84',
    ex2bCond: 'Si tienes piel sensible',
    ex2bVerdict: '68',
    reach: 'Alergias · intolerancias · dieta halal · piel sensible',
    trust: 'Gratis · Sin descargas · Sin publicidad',
    cta: 'Escanear un producto',
    haveAccount: 'Ya tengo cuenta',
    howItWorks: 'Cómo funciona',
  },
  en: {
    brand: 'MASEYA',
    titleTop: 'Scan what you eat and what you put on',
    subtitle: 'and find out if it’s good ',
    subtitleAccent: 'for you',
    ex1Label: 'The same light cheese',
    ex1aCond: 'If you have no allergies',
    ex1aVerdict: '40',
    ex1bCond: 'If you’re lactose intolerant',
    ex1bVerdict: 'Not suitable',
    ex2Label: 'The same cream',
    ex2aCond: 'If your skin is normal',
    ex2aVerdict: '84',
    ex2bCond: 'If you have sensitive skin',
    ex2bVerdict: '68',
    reach: 'Allergies · intolerances · halal diet · sensitive skin',
    trust: 'Free · No downloads · No ads',
    cta: 'Scan a product',
    haveAccount: 'I already have an account',
    howItWorks: 'How it works',
  },
  fr: {
    brand: 'MASEYA',
    titleTop: 'Scanne ce que tu manges et ce que tu mets',
    subtitle: 'et découvre si c’est bon ',
    subtitleAccent: 'pour toi',
    ex1Label: 'Le même fromage light',
    ex1aCond: 'Si tu n’as pas d’allergies',
    ex1aVerdict: '40',
    ex1bCond: 'Si tu es intolérant au lactose',
    ex1bVerdict: 'Non adapté',
    ex2Label: 'La même crème',
    ex2aCond: 'Si ta peau est normale',
    ex2aVerdict: '84',
    ex2bCond: 'Si tu as la peau sensible',
    ex2bVerdict: '68',
    reach: 'Allergies · intolérances · régime halal · peau sensible',
    trust: 'Gratuit · Sans téléchargement · Sans pub',
    cta: 'Scanner un produit',
    haveAccount: 'J’ai déjà un compte',
    howItWorks: 'Comment ça marche',
  },
};
