// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function publicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search MASEYA's product catalog (food & cosmetics) by name or brand. Returns matching products with barcode, name, brand, category, and image.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Product name or brand to search for."),
    category: z.enum(["food", "cosmetic"]).optional().describe("Optional filter: 'food' or 'cosmetic'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const sb = publicSupabase();
    let q = sb.from("maseya_products").select("barcode, product_name, brand, category, image_url, scan_count, verified").or(`product_name.ilike.%${query}%,brand.ilike.%${query}%`).order("scan_count", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function publicSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product by barcode",
  description: "Fetch a MASEYA product's full details (name, brand, category, ingredients, image) by barcode.",
  inputSchema: {
    barcode: z2.string().trim().min(4).describe("Product barcode (EAN/UPC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ barcode }) => {
    const sb = publicSupabase2();
    const { data, error } = await sb.from("maseya_products").select("*").eq("barcode", barcode).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No product found for barcode ${barcode}` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-my-scans.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_scans_default = defineTool3({
  name: "list_my_scans",
  title: "List my scan history",
  description: "Return the signed-in MASEYA user's most recent product scans (barcode, product name, category, score, scan date).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("scan_history").select("id, barcode, product_name, category, product_image, scores, scanned_at").eq("user_id", ctx.getUserId()).order("scanned_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tjimqvdnzjivpgkkyylo";
var mcp_default = defineMcp({
  name: "maseya-mcp",
  title: "MASEYA",
  version: "0.1.0",
  instructions: "MASEYA tools for natural beauty & food product safety. Use `search_products` to find products by name/brand, `get_product` to fetch a product by barcode, and `list_my_scans` to read the signed-in user's scan history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_my_scans_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
